version: '3.8'

services:
  mongo:
    image: mongo:7
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-init:/docker-entrypoint-initdb.d
    environment:
      - MONGO_INITDB_DATABASE=myapp
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    networks:
      - appnet

  app:
    build: .
    env_file:
      - .env
    container_name: go-app
    restart: always
    depends_on:
      - mongo
    ports:
      - "8080:8080"
    environment:
      MONGO_URI: mongodb://mongo:27017
    networks:
      - appnet

networks:
  appnet:
    driver: bridge